# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894f6e0d65b28c08b32d300a36b1408dbee8dcc93d8d22b72aefb75f6f07698265f2bb8382a0f14cd5081d3909b8a089800666ded901a2a6ae77a8b13431c0cb

test:
  secret_key_base: c34a45a19957c6a2fb4565aaa47819d88354ecd0d631cef41a774b92fc2ecd4e7d5513b96326243881e71227e4b39091382ddfd80d3cfc8a2feffec7d61ea308

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
